function [obsBis, obsOx] = readTrainingData()


%read all regions
[~, ~, ~, obsBis_IAP, ~] = ... 
    UIreadDataNew('IAP_BS.txt');
[~, ~, ~, obsOx_IAP, ~] = ... 
    UIreadDataNew('IAP_oxBS.txt');
[~, ~, ~, obsBis_L1mdA, ~] = ... 
    UIreadDataNew('L1mdA_BS.txt');
[~, ~, ~, obsOx_L1mdA, ~] = ... 
    UIreadDataNew('L1mdA_oxBS.txt');
[~, ~, ~, obsBis_L1mdT, ~] = ... 
    UIreadDataNew('L1mdT_BS.txt');
[~, ~, ~, obsOx_L1mdT, ~] = ... 
    UIreadDataNew('L1mdT_oxBS.txt');
[~, ~, ~, obsBis_mSat, ~] = ... 
    UIreadDataNew('mSat_BS.txt');
[~, ~, ~, obsOx_mSat, ~] = ... 
    UIreadDataNew('mSat_oxBS.txt');
[~, ~, ~, obsBis_MuERVL, ~] = ... 
    UIreadDataNew('MuERVL_BS.txt');
[~, ~, ~, obsOx_MuERVL, ~] = ... 
    UIreadDataNew('MuERVL_oxBS.txt');
[~, ~, ~, obsBis_Afp, ~] = ... 
    UIreadDataNew('Afp_BS.txt');
[~, ~, ~, obsOx_Afp, ~] = ... 
    UIreadDataNew('Afp_oxBS.txt');
[~, ~, ~, obsBis_Zim3, ~] = ... 
    UIreadDataNew('Zim3_BS.txt');
[~, ~, ~, obsOx_Zim3, ~] = ... 
    UIreadDataNew('Zim3_oxBS.txt');
[~, ~, ~, obsBis_Ttc25, ~] = ... 
    UIreadDataNew('Ttc25_BS.txt');
[~, ~, ~, obsOx_Ttc25, ~] = ... 
    UIreadDataNew('Ttc25_oxBS.txt');
[~, ~, ~, obsBis_Snrpn, ~] = ... 
    UIreadDataNew('Snrpn_BS.txt');
[~, ~, ~, obsOx_Snrpn, ~] = ... 
    UIreadDataNew('Snrpn_oxBS.txt');

% '/Users/kyriakopou/Documents/Hydroxymethylation/dataFilesNew/newFormat/'

%concatenate all observations
obsBis = cat(3, obsBis_IAP, obsBis_L1mdA, obsBis_L1mdT, obsBis_mSat, obsBis_MuERVL, obsBis_Afp, obsBis_Zim3, obsBis_Ttc25, obsBis_Snrpn);
obsOx = cat(3, obsOx_IAP, obsOx_L1mdA, obsOx_L1mdT, obsOx_mSat, obsOx_MuERVL, obsOx_Afp, obsOx_Zim3, obsOx_Ttc25, obsOx_Snrpn);

end
