function E = myConvErrorsBisAct(convProbs)
%MYCONVERRORSBISACT
%    E = MYCONVERRORSBISACT(C,D,E,G)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    16-Mar-2017 16:15:15

c = convProbs(1);
d = convProbs(2);
e = convProbs(3);
g = convProbs(4);

t2 = c-1.0;
t3 = d-1.0;
t4 = e-1.0;
t5 = g-1.0;
t6 = t2.*t3;
t7 = c.*d;
t8 = t2.*t4;
t9 = c.*e;
t10 = t3.*t4;
t11 = d.*e;
t12 = c.*g;
t13 = t2.*t5;
t14 = d.*g;
t15 = t3.*t5;
t16 = e.*g;
t17 = t4.*t5;
E = reshape([c.^2,-c.*t3,-c.*t4,t12,-c.*t3,t3.^2,t10,-g.*t3,-c.*t4,t10,t4.^2,-g.*t4,t12,-g.*t3,-g.*t4,g.^2,-c.*t2,t7,t9,-c.*t5,t6,-d.*t3,-e.*t3,t15,t8,-d.*t4,-e.*t4,t17,-g.*t2,t14,t16,-g.*t5,-c.*t2,t6,t8,-g.*t2,t7,-d.*t3,-d.*t4,t14,t9,-e.*t3,-e.*t4,t16,-c.*t5,t15,t17,-g.*t5,t2.^2,-d.*t2,-e.*t2,t13,-d.*t2,d.^2,t11,-d.*t5,-e.*t2,t11,e.^2,-e.*t5,t13,-d.*t5,-e.*t5,t5.^2],[16,4]);
