function E = myConvErrorsMSIAct(convProbs)
%MYCONVERRORSMSIACT
%    E = MYCONVERRORSMSIACT(C,D,E,G)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    16-Mar-2017 17:53:12
c = convProbs(1);
d = convProbs(2);
e = convProbs(3);
g = convProbs(4);

t2 = c-1.0;
t3 = d-1.0;
t4 = e-1.0;
t5 = g-1.0;
t6 = t2.*t3;
t7 = c.*d;
t8 = t2.*t4;
t9 = c.*e;
t10 = t3.*t4;
t11 = d.*e;
t12 = c.*g;
t13 = t2.*t5;
t14 = d.*g;
t15 = t3.*t5;
t16 = e.*g;
t17 = t4.*t5;
E = reshape([t2.^2,t6,t8,-g.*t2,t6,t3.^2,t10,-g.*t3,t8,t10,t4.^2,-g.*t4,-g.*t2,-g.*t3,-g.*t4,g.^2,-c.*t2,-d.*t2,-e.*t2,t13,-c.*t3,-d.*t3,-e.*t3,t15,-c.*t4,-d.*t4,-e.*t4,t17,t12,t14,t16,-g.*t5,-c.*t2,-c.*t3,-c.*t4,t12,-d.*t2,-d.*t3,-d.*t4,t14,-e.*t2,-e.*t3,-e.*t4,t16,t13,t15,t17,-g.*t5,c.^2,t7,t9,-c.*t5,t7,d.^2,t11,-d.*t5,t9,t11,e.^2,-e.*t5,-c.*t5,-d.*t5,-e.*t5,t5.^2],[16,4]);
