function E = myConvErrorsOx(convProbs)
%MYCONVERRORSOX
%    E = MYCONVERRORSOX(C,D,F)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    13-Mar-2017 17:16:08

c = convProbs(1);
d = convProbs(2);
f = convProbs(3);


t2 = c-1.0;
t3 = d-1.0;
t4 = f-1.0;
t5 = t2.*t3;
t6 = c.*d;
t7 = c.*f;
t8 = t2.*t4;
t9 = d.*f;
t10 = t3.*t4;
E = reshape([c.^2,-c.*t3,t7,-c.*t3,t3.^2,-f.*t3,t7,-f.*t3,f.^2,-c.*t2,t6,-c.*t4,t5,-d.*t3,t10,-f.*t2,t9,-f.*t4,-c.*t2,t5,-f.*t2,t6,-d.*t3,t9,-c.*t4,t10,-f.*t4,t2.^2,-d.*t2,t8,-d.*t2,d.^2,-d.*t4,t8,-d.*t4,t4.^2],[9,4]);
